### ISSUE TITLE
Problem getting length of list

### ISSUE THREAD

**Issue by Gerhman** [tjvr/kurt#25]
I am finding it impossible to write a parseable script that utilizes the length of a list. If I stringify an example I get "length of Randomlist". If I try to parse this though then I get an error claiming that Randomlist is an unknown block. If I put () around the name then it parses but it then uses string length measurer instead of the list one and this does not work.

**Comment by tjvr** [comment]
Closing in favour of [tosh](http://tosh.tjvr.org/)
