### ISSUE TITLE
Scratch 3 Support

### ISSUE THREAD

**Issue by CosmicWebServices** [tjvr/kurt#33]

**Comment by Tymewalk** [comment]
I don't think it's really possible until we know a little more about Scratch 3's .sb3 design.

We have the block format XML (equivalent of the JSON file in sb2s), but nothing else yet.

**Comment by CosmicWebServices** [comment]
That is kind of what I meant we have a working scratch-vm and by what I was looking at the .sb3 files are going to be those xml files

**Comment by Tymewalk** [comment]
@CosmicWebServices Yes, but we don't know how images, sounds, etc. are going to be stored.

That's one of the big uses of Kurt - importing a bunch of images without crashing things.

**Comment by CosmicWebServices** [comment]
Oh OK
