### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by BookOwl** [tjvr/kurt#37]
Your docs seem to be extremely lacking...

**Comment by tjvr** [comment]
readthedocs appears to have gone wrong :-(

There's comprehensive API a documentation—or supposed to be!—but something's gone wrong with sphinx or readthedocs somehow. You're welcome to help look into it if you want :-)

**Comment by BookOwl** [comment]
I remember the API documentation being very good before, that's why I was so surprised when I found it all gone! I'll see if I can find what's wrong.

**Comment by BookOwl** [comment]
Cloning the repo and running `make html` in the docs directory makes the right docs.

**Comment by heyitsmeuralex** [comment]
@tjvr pls

**Comment by tjvr** [comment]
I don't have time to fix this right now. If either of you can figure it out I'd appreciate it. :-)

**Comment by raulperula** [comment]
Hi! How could we fix it? I've done the "make html" in my fork and it works but I do not know to fix the problem in the original repo.

If you can tell me the steps I could try.

**Comment by tjvr** [comment]
Argh. I’ll try fiddling with the RTD settings later (assuming I can still log in!). :-)

**Comment by raulperula** [comment]
Perfect. Thank you.

If you need any help, please tell us!

**Comment by tjvr** [comment]
All fixed. Looks like I didn't specify a version for `construct`! fcccd80

I have no idea how this worked before...or maybe it's been broken for years? :P

This would've been quicker to resolve if I hadn't forgotten how RTD works—and the `ImportErrors` it raised were more easily visible in the Settings. Ah well...
