### ISSUE TITLE
it keeps resetting my WI-FI

### ISSUE THREAD

**Issue by PiotrGrochowski** [tjvr/kurt#43]
![image](https://user-images.githubusercontent.com/7955653/38452646-6c3091f6-3a48-11e8-917d-5db32e140f38.png)
My Wi-Fi apparently resets frequently, preventing the page from loading!!?

**Comment by tjvr** [comment]
This isn't really the right place to report this. Perhaps your project is too big?

Anyway, I've recently moved from Heroku to my own server, so maybe you'll have better luck with it now!
